### ISSUE TITLE
Dockerize .net core 2 and node npm

### ISSUE THREAD

**Issue by spk27** [antonioortizpola/cero-uno-c-sharp-architecture#9]
Hi tony!! hope you are fine!
Guest if you can help me into this..
I have been trying to dockerize and app web on .net core 2.1 and vue based, running and working ok on release! ... whathever when i run the docker-composer that is "microsoft/dotnet:2.1-aspnetcore-runtime" based it works until it needs install the the NPM dependencies for the javascript framework and throws.
I have been looking for some questions but it is not clear to me.. meanwhile it is a long process (like 1 hour) for dockerize this until it throws.
this is my dockerfile

```

 FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
 WORKDIR /app
 EXPOSE 80

 FROM microsoft/dotnet:2.1-sdk AS build
 WORKDIR /src
 COPY FacturaPrueba/Facturar.csproj FacturaPrueba/
 COPY Persistencia/Persistencia.csproj Persistencia/
 COPY some five projects more.....

 RUN dotnet restore FacturaPrueba/Facturar.csproj
 COPY . .
 WORKDIR /src/FacturaPrueba
 RUN dotnet build Facturar.csproj -c Release -o /app

 FROM build AS publish
 RUN dotnet publish Facturar.csproj -c Release -o /app

 FROM base AS final
 WORKDIR /app
 COPY --from=publish /app .
 ENTRYPOINT ["dotnet", "Factura.dll"]

```

it is linux based... i have just node and npm install via yarn or apt-get??
that's the correct way? where would i put it in my docker file? figure that the NPM install is in the pipeline of the "Facturar.csproj", it runs when "Facturar.csproj" is building

Thanks Tony!

**Comment by antonioortizpola** [comment]
Sorry for the late answer, it is been a long and heavy week.
Just some more info, How are you working the vue part? is a Node server or the same C# app the one that renders the front end? The API is in the same project?
I ask this questions since there is no "correct" approach and as many things, will "depend" on the specific case. Having said that, i have been seen some predominant patterns, which looks promising.

> I have to repeat, this is not the ideal answer, it is more like a guideline or a recipe to starts dealing with this world of docker and micro-services.

Remember, the predominant idea is "divide and conquer", as with your code, the same with your infrastructure, docker will always gonna try to push you this side, considering each element of your infrastructure as independent elements that can be handled separate.

The advantages will be more order when the system start to scale, if each service is keep independent, it can scale and grow according to their needs, if you have a ton of clients checking some data, you can scale your front end services, if you have a few clients doing heavy processing, then you can scale your api service. As the organization grow, the infrastructure can grow in the parts where it matter.

To handle this services you will need to check [Docker-Compose](https://docs.docker.com/compose/), this way you will be connecting your services, a very efficient pattern to create apps is something as follows:
![basicarchitecture](https://user-images.githubusercontent.com/11655127/42406290-388a02e2-816a-11e8-8dc8-680ffdd63756.png)

Each one of this rectangles are a component, each component can be a docker image or a docker-compose file itself, this makes simple to grow or change the stack if something in the future changes, for example, you could eventually use a third provider for traffic redirection and load balancing like Amazon cloudfront or cloudfare, or just a different server, same with the databases or the applications itself.

Creating all of this infrastructure with docker and docker-compose allows to start small, with a simple computer and server, and move around and scale with easy and a lot of tools.

For example, we have a system with two mysql databases and a redis used as cache and source of truth across servers, this way we can scale each database or app as required, to start our development we do not need to install all this applications, we can use our `DockerComposeDev.yml`:

```
version: '3.4'

services:
  vtae.redirect.redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
      
  mysql:
    image: mysql
    command: "--innodb_use_native_aio=0"
    volumes:
      - ./volumes/mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: xyzDatabase
      MYSQL_USER: xyzUser
      MYSQL_PASSWORD: xyzPassword
    ports:
     - '3306:3306'
     
     
  mysql-stats:
    image: mysql
    command: "--innodb_use_native_aio=0"
    volumes:
      - ./volumes/mysqlstats/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: xyzDatabaseStats
      MYSQL_USER: xyzUser
      MYSQL_PASSWORD: xyzPassword
    ports:
     - '3307:3306'
```

After run `docker-compose -f DockerComposeDev.yml up` (optionally -d to run as daemon) we have our environment ready to develop, and we can be certain that the same versions of the same software will be run in the production server.

So we just need our `DockerComposeProd.yml`, this will be somehow like the dev file, adding the **net core** application itself, but removing those services that are not necessary for production, for example, in our application we are using _Amazon RDS_ to manage the database, so the sql services are no longer necessary:

```
version: '3.4'

services:  
  vtae.redirect.redis:
    image: redis
    volumes:
      - "./volumes/redirect/redis/data:/data"
    container_name: my.app.redis
      
  my.app:
    image: my.app
    depends_on:
      - my.app.redis
    build:
      context: .
      dockerfile: my.app/Dockerfile #This is the docker file of the net core app
    ports: 
      - "8080:80"
    volumes:
      - "./volumes/myapp/data:/data"
    container_name: my.app
    entrypoint: dotnet /app/my.app.dll
```

Eventually we will move Redis out to use Redis as service from Amazon, so only the removal from the dockerfile and the modification of the configurations will be necessary.

It seems weird that the app takes that long for the build, maybe the first time when it download the images, but it  should not be that long, our setup is very similar to yours, and it is taking 7 minutes to build, building three different projects
![screenshot_4](https://user-images.githubusercontent.com/11655127/42406474-091ce052-816e-11e8-9bd5-9b19fec91106.png)

It should be interesting to check the output and search which part is the one causing the delays, I do not know if could answer some of your questions, but feel free to comment and let me know if i can help you with something more!.

Other thing that comes to my mind, if you need node to manage your net core app resources, yes you need to install it, the last time i checked, **the default net core image in docker is based in debian**, so you need to use apt-get to install it, but to reduce the build time, i would recommend you to create a custom image, just:
- Run the core container
- Attach and make all the modifications you need
- Push the container as image
- Use this image instead the net core for the build phase
